# runs 12pm UTC Mon-Thu (early morning PT)
name: Scheduled find offline LHTP links and images

on:
  schedule:
    - cron: '0 12 * * 1-4'

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Set up SSH for Git operations
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.CODE_REVIEWS_REPO_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Run script
        run: npm run start
        env:
          NODE_ENV: 'production'
          ORG: ${{ secrets.ORG }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          CC: ${{ secrets.CC }}
