# runs 12pm UTC Mon-Thu (early morning PT)
name: Scheduled find offline LHTP links and images

on:
  schedule:
    - cron: '0 12 * * 1-4'

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Generate GitHub App token
        uses: peaceiris/actions-github-app-token@v1
        id: github-app-token
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_id: ${{ secrets.INSTALLATION_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Run script
        run: npm run start
        env:
          GITHUB_APP_TOKEN: ${{ steps.github-app-token.outputs.token }}
          NODE_ENV: 'production'
          ORG: ${{ secrets.ORG }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          FROM: ${{ secrets.FROM }}
          TO: ${{ secrets.TO }}
          CC: ${{ secrets.CC }}
